### ISSUE TITLE
Failed to initialize D3D11Device

### ISSUE THREAD

**Issue by DexiTheZombie** [RussellJerome/UnrealModLoader#10]
Getting This error when loading with the fnaf9 profile
[UML-Log.txt](https://github.com/RussellJerome/UnrealModLoader/files/7797399/UML-Log.txt)
.

**Comment by RussellJerome** [comment]
This is not a UML issue, UML at the moment doesn't work with Direct X 12, you would have to start the game in Direct X 11 Mode. If you have any more issues feel free to join the support server.
https://discord.gg/UGMTYb6n
