### ISSUE TITLE
Adding recursivity in CoreMods folder

### ISSUE THREAD

**Issue by tsukasaroot** [RussellJerome/UnrealModLoader#20]
Hello, it would be cool to look recursively for mods inside this folder, or atleast one folder down, as I plan to have a soft that will handle mods management automatically and want the architecture to be clean.

It would be something like : 
GameFolder\Content\CoreMods\mod_folder_name\mod_files_content

**Comment by RussellJerome** [comment]
Thanks for the suggestion, ill look more into it however I would recommend you post suggestions in the discord server as I am more likely to see it there :P

https://discord.gg/Udy4aH5A3Q
